### ISSUE TITLE
Server timeouts when uploading bigger datasets

### ISSUE THREAD

**Issue by jluethi** [pelkmanslab/TissueMAPS-OLD#15]
I tried uploading the NUP screen in the last few days. It's 10 plates, ~100 GB each. I try uploading one plate at a time with the tm_client, but always run into server timeouts. Sometimes, it just doesn't upload anything for 10 minutes (see time stamps on this first screenshot)
![screen shot 2017-01-25 at 15 24 37](https://cloud.githubusercontent.com/assets/18033446/22344321/0c84d4ea-e3fc-11e6-82cb-1a943e78b5e2.png)

And sometimes, it crashes with different server errors:
502 Server Error: Bad Gateway (after having uploaded hundreds of images already)
504 Server Error: Gateway Time-out for url

![screen shot 2017-01-24 at 17 46 05](https://cloud.githubusercontent.com/assets/18033446/22344372/3f81614c-e3fc-11e6-923b-3067dded286a.png)
![screen shot 2017-01-25 at 15 24 48](https://cloud.githubusercontent.com/assets/18033446/22344373/3f9e0748-e3fc-11e6-974e-4a1360d8623a.png)

**Comment by jluethi** [comment]
Still happening to me & Chris.
Now for both of us with Error 400

![screen shot 2017-01-27 at 14 18 11](https://cloud.githubusercontent.com/assets/18033446/22372450/0c70459c-e49d-11e6-860e-f3be50f69e79.png)

**Comment by Christophe-Freyre** [comment]
![error 400](https://cloud.githubusercontent.com/assets/11965283/22372559/c3ef49b6-e49d-11e6-8fb7-5d8ef343e537.png)

At a different time apparently (14:08:13 vs 14:12:12)

**Comment by SaadiaIftikhar** [comment]
Please restart the upload, if it hangs. It will start from where it was stalled.

**Comment by scottberry** [comment]
This is also an issue for me when uploading from tm_client instance on ScienceCloud (data stored in pelkmans lab science cloud storage and mounted via smb)

**Comment by hackermd** [comment]
What's the status on this issue?

**Comment by jluethi** [comment]
I haven't had any issues with this anymore. As long as I upload from Science Cloud shares, the upload is very fast & doesn't run into timeouts.

**Comment by hackermd** [comment]
Ok! Great! I close this issue then.
