### ISSUE TITLE
workflow continuously processing on pyramid creation on small test datasets 

### ISSUE THREAD

**Issue by SaadiaIftikhar** [pelkmanslab/TissueMAPS-OLD#28]
I put 8 images and one image dataset (2d and 3d) separately on two virtual machines for tests purpose, it continuously processing on pyramid creation stage. 

In the logs, I receive:

2017-02-19 21:15:51 | ERROR    | gc3.gc3libs                       | Invalid state ''NEW'' returned by task 25.
2017-02-19 21:15:51 | ERROR    | gc3.gc3libs                       | Invalid state ''NEW'' returned by task 27.

**Comment by scottberry** [comment]
Check that the disk is not full. I had a similar problem once the database filled up the root disk on my test instance.

**Comment by SaadiaIftikhar** [comment]
Filesystem                                        1K-blocks     Used  Available Use% Mounted on
sysfs                                                     0        0          0    - /sys
proc                                                      0        0          0    - /proc
udev                                               16016592       12   16016580   1% /dev
devpts                                                    0        0          0    - /dev/pts
tmpfs                                               3204360      580    3203780   1% /run
/dev/vda1                                         103178528 17331944   81621624  18% /
none                                                      4        0          4   0% /sys/fs/cgroup
none                                                      0        0          0    - /sys/fs/fuse/connections
none                                                      0        0          0    - /sys/kernel/debug
none                                                      0        0          0    - /sys/kernel/security
none                                                   5120        0       5120   0% /run/lock
none                                               16021796        8   16021788   1% /run/shm
none                                                 102400        0     102400   0% /run/user
none                                                      0        0          0    - /sys/fs/pstore
//testdata.tissuemaps.org/tmaps-testdata-share-1 2113654704  1519788 2004744452   1% /home/ubuntu/shares/testdata
systemd                                                   0        0          0    - /sys/fs/cgroup/systemd

**Comment by SaadiaIftikhar** [comment]
I have just one field (image), dataset. Literally just one image for testing the workflow. I put it to test that everything goes through!

**Comment by SaadiaIftikhar** [comment]
@scottberry, @riccardomurri , @alecrimi, @HackerMD

**Comment by hackermd** [comment]
This can occur when tasks where deleted from the database table, but they are still in the engine in memory. Restart the server.

@riccardomurri an example of why I think store and engine should be more strongly coupled together.

**Comment by SaadiaIftikhar** [comment]
I rebooted machine, it still is in pyramid creation stage and the same error as above. I can't resumbit the jobs as well.

**Comment by hackermd** [comment]
Delete all submissions and restart the server:

```
$ db -c 'DELETE FROM submissions'
$ ./stop_server
$ ./start_server
```

**Comment by scottberry** [comment]
Ok, perhaps this is a bug related to building a pyramid from a single image?

**Comment by SaadiaIftikhar** [comment]
I deleted the submissions and rebooted the server, still the same error:

2017-02-20 12:52:13 | ERROR    | gc3.gc3libs                     | Invalid state ''NEW'' returned by task 61.
2017-02-20 12:52:13 | ERROR    | gc3.gc3libs                     | Invalid state ''NEW'' returned by task 63.

**Comment by hackermd** [comment]
This might be due to a GC3Pie "feature":

```
$ ./stop_server
$ db -c 'DELETE FROM submissions'
$ rm -rf ~/.gc3/shellcmd.d
$ ./start_server
```

**Comment by SaadiaIftikhar** [comment]
The same dataset, I was able to create pyramids, last week (Monday/ Tuesday), 13th or 14 Feb. But since, Thursday/Fri, this is stopping on the pyramid creation.

**Comment by hackermd** [comment]
So far, you've only been describing an error related to GC3Pie. Can you be more specific, please?

- git commit tags
- logs & error traceback

**Comment by SaadiaIftikhar** [comment]
I have created instance on
OK, 
I build the VM with the image: tissuemaps-v0.2.0[dev][2]  on tissuemaps.org tenant. 

ssh it and did the following command to pull the latest tmlibrary in it.

./stop_server.sh
cd tmlibrary/
git pull
cd
cd tmserver/
git pull
cd
./start_server.sh

**Comment by SaadiaIftikhar** [comment]
new virtual machine, tissuemaps-saadia-server-001,  worked for 3D visualization as well as it not stopping in the middle of workflow.  @scottberry .

**Comment by scottberry** [comment]
@SaadiaIftikhar It would be useful to reference the current versions of git repos in which the bug is resolved. You can get these from the current instance
