### ISSUE TITLE
Batch size not visible in illumination correction

### ISSUE THREAD

**Issue by scottberry** [pelkmanslab/TissueMAPS-OLD#30]
Cannot specify the batch size for illumination correction. 

![screen shot 2017-02-20 at 11 16 11](https://cloud.githubusercontent.com/assets/5407848/23120794/180a39ca-f75e-11e6-803f-5c954637cd77.png)

**Comment by hackermd** [comment]
This is correct, since the `corilla` step doesn't have any `BatchArguments`.
