### ISSUE TITLE
tmclient fails when filename contains a #

### ISSUE THREAD

**Issue by jluethi** [pelkmanslab/TissueMAPS-OLD#41]
The tmclient fails in the upload again when the filename contains a #. It tries to upload a file without the # and thus does not find that file.

@HackerMD Didn't you solve that problem once? Can you fix it again?

Here is an example:
Filename is AssayPlate_Greiner_#781091_C03_T0001F013L01A01Z01C01, but it searches for AssayPlate_Greiner_781091_C03_T0001F013L01A01Z01C01

![screen shot 2017-02-24 at 16 38 03](https://cloud.githubusercontent.com/assets/18033446/23309685/fc7defe4-faaf-11e6-8cdd-37fec7179c3b.png)

@alecrimi

**Comment by hackermd** [comment]
This is related to passing filenames through [secure_filename()](http://werkzeug.pocoo.org/docs/0.11/utils/#werkzeug.utils.secure_filename) server side. Should be fixed with TissueMAPS/TmClient@8ff057cf3c97c1b25baf99de84f6d0eadd32507e. For the future, I would try to avoid insecure filenames.
