### ISSUE TITLE
Image conversion not finding tmlibrary

### ISSUE THREAD

**Issue by alecrimi** [pelkmanslab/TissueMAPS-OLD#45]
Image conversion is giving this error not finding tmlibrary. Tmlibrary has been installed using pip -V
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

as "sudo pip install ."

@HackerMD @ggut @apiehl 

> Traceback

 (most recent call last):
  File "/home/ubuntu/.local/bin/metaextract", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2994, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2980, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3007, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 852, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tmlibrary' distribution was not found and is required by the application

**Comment by hackermd** [comment]
Is this on the cluster?

Why do you install with `sudo`. We always install with the `--user` flag, because the `$HOME` directory is exported on the cluster.

**Comment by alecrimi** [comment]
It is on the front-end chimp cluster.
After I tried pip install . --user I got this: Perfect!

--- no python application found, check your startup logs for errors ---
[pid: 1834|app: -1|req: -1/65] 130.60.76.83 () {42 vars in 881 bytes} [Tue Feb 28 15:18:06 2017] GET /api/experiments/dG1hcHM4/workflow/status => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 99)

**Comment by alecrimi** [comment]
These last pip install broke something in the uwsgi.ini or something related not sure what.
Are we using Flask or something similar in Chimp? which environment?

**Comment by alecrimi** [comment]
now tmlib has been found but it seems that tmlib is looking for pyfakefs. @jluethi 
Typing "pip freeze " to list all pip or easy_install package, I found that there is a previous version on Chimp installed as 
"-e git+https://github.com/TissueMAPS/TmLibrary.git@23fb074951504235deb4e6f8b172518dd8d05a86#egg=tmlibrary"
This might still be the old version to be eliminated since this was installed as
" sudo pip install -e git+https://github.com/TissueMAPS/TmLibrary.git#egg=tmlibrary --process-dependency-links" and pyfakefs is one of this dependencies

pip list is instead listing correctly:
tmlibrary (0.2.0, /home/ubuntu/tmlibrary)

Or maybe this are properly installed and the issue with pyfakefs is from somewhere else

**Comment by alecrimi** [comment]
This has to be solved as It looks like TM is still using a previous installation of tmlib

**Comment by alecrimi** [comment]
I have removed tmlibrary as "sudo pip uninstall tmlibrary".
Then I typed: pip install . --user
which gave several lines like this:

> Requirement already satisfied: toolz>=0.7.2; extra == "array" in /home/ubuntu/.local/lib/python2.7/site-packages (from dask[array]>=0.5.0->scikit-image>=0.12.0->tmlibrary==0.2.0)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python2.7/dist-packages (from setuptools>=0.7->APScheduler>=3.0.5->tmlibrary==0.2.0)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools>=0.7->APScheduler>=3.0.5->tmlibrary==0.2.0)
Requirement already satisfied: humanfriendly>=2.1 in /home/ubuntu/.local/lib/python2.7/site-packages (from coloredlogs->gc3pie==2.5.dev->tmlibrary==0.2.0)
Requirement already satisfied: lockfile>=0.10 in /home/ubuntu/.local/lib/python2.7/site-packages (from python-daemon->gc3pie==2.5.dev->tmlibrary==0.2.0)

so it seems the library was still there.
Then I did the same with tmserver, and I got this:
Collecting tmlibrary>=0.1.0 (from tmserver==0.1.0)
  Could not find a version that satisfies the requirement tmlibrary>=0.1.0 (from tmserver==0.1.0) (from versions: )
No matching distribution found for tmlibrary>=0.1.0 (from tmserver==0.1.0)

I think this nfs server copying stuff on the worker nodes, is messing up something

**Comment by alecrimi** [comment]
even more spooky:
if I install tmlibrary, they appear on the list from "pip list", if I then try to install tmserver, they disappear,

**Comment by alecrimi** [comment]
I had to clean up all tmserver and tmlibs installations, in .local and on root folder. And put them from scratch. Now it is fine.
