### ISSUE TITLE
tm_client crashes if non wanted files are in upload directory

### ISSUE THREAD

**Issue by jluethi** [pelkmanslab/TissueMAPS-OLD#52]
If there are files that are not supposed to be uploaded, tmclient ( https://github.com/TissueMAPS/TmClient/commit/1e3232e5089b35ec2378d4fb8b82e35f221a6715 ) fails with a 500 server error, every time a file that is not one of the actual image files comes up.

A workaround for the moment is: Move the other files out of the directory, into a separate folder.

@HackerMD Do you know why it fails there?

![screen shot 2017-03-08 at 16 51 21](https://cloud.githubusercontent.com/assets/18033446/23711710/ecacdf6a-0420-11e7-9bf9-6f0b719c187f.png)

**Comment by hackermd** [comment]
This should be resolved by TissueMAPS/TmClient@8ff057cf3c97c1b25baf99de84f6d0eadd32507e. @jluethi can we close this issue?

**Comment by jluethi** [comment]
Yes, this is fixed and works now!
