### ISSUE TITLE
Standard output and standard error are not displayed in User interface anymore

### ISSUE THREAD

**Issue by jluethi** [pelkmanslab/TissueMAPS-OLD#56]
While standard output and standard error files are still saved on the tissuemaps server, they are not displayed in the interface anymore and there is no error on the console.

<img width="904" alt="screen shot 2017-03-24 at 17 06 20" src="https://cloud.githubusercontent.com/assets/18033446/24302934/986ba594-10b4-11e7-8abc-9117438c600b.png">

**Comment by hackermd** [comment]
You probably updated `tmserver` without updating `tmui`. I recently changed some URLs, see TissueMAPS/TmUI@33fe3db

**Comment by jluethi** [comment]
No, at least at this moment, both tmserver and tmui are up to date on the master branch and the std. output & std. error is still empty.
I traced the problem down to either SetupCtrl.ts (which defines the getLogOutput function) or to RunnerCtrl.js (which seems to define how the job output gets extracted).

To be able to debug this, I added console.log entries into SetupCtrl.ts, but I can’t get my log statements to be shown in the console (even if I e.g. change an existing log statement that I see getting called).

I have tried stopping the server, restarting nginx & uwsgi and then starting the server again, but that doesn’t help. Can you let me know how I can make my changes apply?

**Comment by hackermd** [comment]
Did you also build the new client code? The app is written in TypeScript and needs to be compiled via `gulp`:

```
cd ~/tmui/src
rm -r build
gulp build --production
```

This would also explain why your log statements are not getting called.

**Comment by jluethi** [comment]
Thanks a lot, I was not aware of that! I haven't done that, so that makes sense.

**Comment by hackermd** [comment]
Fixed with TissueMAPS/TmUI@c5d866334efadaeac8ef0085dac9bd087e61af87
