### ISSUE TITLE
Border cells: only bottom & right borders intersect with cells

### ISSUE THREAD

**Issue by jluethi** [pelkmanslab/TissueMAPS-OLD#58]
@HackerMD 
Currently, the border cell detection only works for bottom and right border. The top and the left border is not detect. I suspect that if you shrank the site border by 1 pixel, it only fixed two sides. Most likely, the site border needs to be shrunk by 1 pixel again, but this time from the top and the right side (while keeping bottom & left at the same location).

**Comment by hackermd** [comment]
Fixed with TissueMAPS/TmLibrary@9ba89f04e40e69fd0a667a1deb21643a7d2cec23
