### ISSUE TITLE
Using 4-connected component labeling

### ISSUE THREAD

**Issue by hackermd** [pelkmanslab/TissueMAPS-OLD#69]
Shall we switch to 4-connected component labeling? The reason why I implemented 8-connected labeling was compatibility with Matlab, which performs 8-connected labeling by default.

**Comment by jluethi** [comment]
I will test this now, to see whether it breaks anything. Of the top of my head, I can't think of a case where 8-connected labeling would be necessary, but there are edge cases where it may lead to unexpected results (see picture).
![img_3153](https://cloud.githubusercontent.com/assets/18033446/25476762/7fafa52c-2b3b-11e7-9bf3-3f053cf5340e.jpg)

**Comment by hackermd** [comment]
I've added a `connectivity` parameter to the label module: TissueMAPS/JtModules@b3ce49ed7f8dd1c0cfeaf615f2fcdecd8abfd302.

**Comment by jluethi** [comment]
Cool, I'll be trying that out soon. I now have a setup on the jupyter machine that lets me plot my segmentations after the different steps, so I can look for differences
