### ISSUE TITLE
Segmentation modules on Jterator

### ISSUE THREAD

**Issue by alecrimi** [pelkmanslab/TissueMAPS-OLD#7]
Testing modules. Do they work well? How do the modules compare to cell segmentation in iBrain BRUTUS (identify_primary_iterative and identify_secondary_iterative). The modules in iBrain are however very slow and can be much improved.

**Comment by SaadiaIftikhar** [comment]
Posted the segmentation modules in the github. Added the modules in the gorilla for the tests. In Jterator, these modules are not appearing in the list of modules yet.

**Comment by SaadiaIftikhar** [comment]
Done! The code is in github including their handles. Working fine, for me.

**Comment by liberali** [comment]
It needs o be tested by users
